#!/usr/bin/env bash
# ARMOR-RADAR - gives a node its identity on the bench broker and writes its settings file.
# Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
#
#   tools/provision_node.sh perimetro-1 --host 192.168.0.180 --user <user> --key ~/.ssh/id_key [--broker-host 192.168.0.180]
#
# Runs ARMOR-DEVOPS's mqtt_identity.sh on the test bench over SSH (its own sudo), captures the password it prints once, and writes it
# straight into secrets/<node>.conf (mode 600, git-ignored), together with a setup code for the node's first administrator. Neither is shown on the
# screen: the build puts them in the node as its FIRST settings, and from then on the node's own web panel is where they change. If the identity already exists
# the script stops: remove it first (mqtt_identity.sh remove field-node-<node>) to get a new password.
set -euo pipefail
NODE="${1:-}"; shift || true
[[ "$NODE" =~ ^[a-z0-9][a-z0-9_-]{0,63}$ ]] || { echo "usage: provision_node.sh NODE_ID --host H --user U [--key K] [--broker-host B] [--broker-port 18883]" >&2; exit 2; }
HOST=""; USER_NAME=""; KEY=""; BROKER_HOST=""; BROKER_PORT="18883"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --host) HOST="$2"; shift 2 ;;
    --user) USER_NAME="$2"; shift 2 ;;
    --key) KEY="$2"; shift 2 ;;
    --broker-host) BROKER_HOST="$2"; shift 2 ;;
    --broker-port) BROKER_PORT="$2"; shift 2 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done
[[ -n "$HOST" && -n "$USER_NAME" ]] || { echo "--host and --user are required" >&2; exit 2; }
BROKER_HOST="${BROKER_HOST:-$HOST}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/secrets/$NODE.conf"
[[ ! -e "$OUT" ]] || { echo "$OUT already exists; delete it (and remove the broker identity) to start over" >&2; exit 1; }
SSH_OPTS=(-o BatchMode=yes -o ConnectTimeout=10); [[ -n "$KEY" ]] && SSH_OPTS+=(-i "$KEY")

IDENTITY_SCRIPT="$ROOT/../ARMOR-DEVOPS/scripts/mqtt_identity.sh"
[[ -f "$IDENTITY_SCRIPT" ]] || { echo "ARMOR-DEVOPS/scripts/mqtt_identity.sh not found next to this repository" >&2; exit 1; }
# The script is sent over SSH and run with the deploy user's sudo: nothing is left on the bench computer.
RESULT="$(ssh "${SSH_OPTS[@]}" "$USER_NAME@$HOST" "sudo bash -s -- add node $NODE" <"$IDENTITY_SCRIPT" 2>&1)" || { echo "the broker refused: $(echo "$RESULT" | sed 's/password: .*/password: (hidden)/')" >&2; exit 1; }
# mosquitto_passwd may print a warning without a newline just before these lines, so they are picked out of the text, not by line start.
USER_LINE="$(printf '%s\n' "$RESULT" | grep -o 'user: field-node-[a-z0-9_-]*' | head -1 | sed 's/^user: //')"
PASS_LINE="$(printf '%s\n' "$RESULT" | grep -o 'password: [A-Za-z0-9]\{16,64\}' | head -1 | sed 's/^password: //')"
[[ -n "$USER_LINE" && -n "$PASS_LINE" ]] || { echo "the broker did not return an identity" >&2; exit 1; }

# The setup code: 10 characters without look-alikes (no 0, O, 1, I, L). It lets the first administrator be created from the panel of a node
# that has no cable to a console; the node accepts it only while it has no user.
SETUP_CODE="$(LC_ALL=C tr -dc 'A-HJKMNP-Z2-9' </dev/urandom | head -c 10)"
[[ ${#SETUP_CODE} -eq 10 ]] || { echo "could not make a setup code" >&2; exit 1; }

mkdir -p "$ROOT/secrets"
( umask 077
  {
    echo "# Settings of node $NODE. Generated by tools/provision_node.sh; git-ignored."
    echo "CONFIG_ARMOR_NODE_ID=\"$NODE\""
    echo "CONFIG_ARMOR_MQTT_URI=\"mqtt://$BROKER_HOST:$BROKER_PORT\""
    echo "CONFIG_ARMOR_MQTT_USERNAME=\"$USER_LINE\""
    echo "CONFIG_ARMOR_MQTT_PASSWORD=\"$PASS_LINE\""
    echo "CONFIG_ARMOR_SETUP_CODE=\"$SETUP_CODE\""
    echo "CONFIG_ARMOR_RADAR_COUNT=3"
  } >"$OUT" )
echo "wrote $OUT (identity $USER_LINE; the password and the setup code are only in that file)"
